### PR TITLE
Feat/search

### PR DESCRIPTION
**Pull request by jamarob**
I added a search state and its input field to filter characters by name.

### CODE REVIEW

**Comment by lindatroesken** [comment]
Approved

**Comment by Droggelbecher92** [comment]
Supi!

**Comment by AdrianaSche** [comment]
danke!

**Comment by TomZe1982** [comment]
Juhu!

**Comment by guillermo-ctrl** [comment]
ok

**Review by LeonTheCreator — COMMENTED** [review]
Bestimmt alles Super! ;-)

**Review by Alessandra-Ipiranga — COMMENTED** [review]
Super gemacht! :+1:

**Pull request merged**
